#ifndef TEMPORALIO_PERL_BRIDGE_H
#define TEMPORALIO_PERL_BRIDGE_H

/* Generated by cbindgen from temporalio-perl-bridge — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TemporalCoreByteArray TemporalCoreByteArray;
typedef struct TemporalCoreConnection TemporalCoreConnection;
typedef struct TemporalCoreEphemeralServer TemporalCoreEphemeralServer;
typedef struct TemporalCoreWorkerOptions TemporalCoreWorkerOptions;

/**
 * `kind` discriminator values, 1..6 in spec section 3 trampoline order, plus
 * the kind-7 log-forwarding entry (spec section 28.1). Kind 7 differs from
 * 1..6: it carries no `callback_id` (no pending Future) and owns its buffers
 * shim-side, freed via `temporalio_perl_bridge_forwarded_log_free`.
 */
#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER_POLL 1

#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER 2

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_CONNECT 3

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_RPC_CALL 4

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_START 5

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_SHUTDOWN 6

#define TEMPORALIO_PERL_BRIDGE_KIND_FORWARDED_LOG 7

/**
 * Thread-safe completion queue: an unbounded `SegQueue` plus the signal fd.
 * One allocation per `Temporalio::Core::Runtime` instance.
 */
typedef struct TemporalioPerlBridgeQueue TemporalioPerlBridgeQueue;

/**
 * Opaque borrow of sdk-core-c-bridge's `ForwardedLog`. The shim never
 * dereferences this — it only passes the pointer back to core's
 * `temporal_core_forwarded_log_*` accessors, which are valid only for the
 * duration of the `forward_to` callback (the log is freed the instant the
 * callback returns).
 */
typedef struct TemporalCoreForwardedLog {
  uint8_t _private[0];
} TemporalCoreForwardedLog;

/**
 * One queued completion. `kind` discriminates which trampoline fired (1..6)
 * and therefore which fields are meaningful. ByteArray pointers must be
 * freed by the Perl side via `temporal_core_byte_array_free`.
 */
typedef struct TemporalioPerlBridgeEntry {
  uint64_t callback_id;
  /**
   * Tagged union discriminator, 1..6 in trampoline declaration order.
   */
  uint8_t kind;
  /**
   * Common: success / fail byte arrays (null when absent).
   */
  const TemporalCoreByteArray *success_ba;
  const TemporalCoreByteArray *fail_ba;
  /**
   * Client connect / ephemeral server start success handle.
   */
  void *success_handle;
  /**
   * RPC call extras (fail_ba carries the failure_message). For a kind-7
   * forwarded-log entry, `rpc_status_code` carries the forwarded log level
   * (0..4 = Trace..Error).
   */
  uint32_t rpc_status_code;
  const TemporalCoreByteArray *rpc_failure_details;
  /**
   * Ephemeral server start target string.
   */
  const TemporalCoreByteArray *ephemeral_target;
  /**
   * Kind-7 forwarded-log payload (spec section 28.1). These three buffers
   * are deep copies owned by the shim (NUL-terminated C strings), freed by
   * `temporalio_perl_bridge_forwarded_log_free` after the Perl drain reads
   * them, or by `Entry::drop` for undrained entries at queue free. They are
   * null for every kind other than 7.
   */
  char *log_target;
  char *log_message;
  char *log_fields_json;
  /**
   * Kind-7 forwarded-log timestamp (milliseconds since the Unix epoch).
   */
  uint64_t log_timestamp_ms;
} TemporalioPerlBridgeEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Claim the process-global forwarding registry for `q`, recording the four
 * core accessor function pointers (passed as opaque from Perl). Returns true
 * on success, false if a runtime already forwards logs (the caller raises
 * Argument). The compare-and-set on the active flag makes the claim race-free
 * across runtimes constructed concurrently.
 *
 * # Safety
 * The four pointers must be the live `temporal_core_forwarded_log_*` symbols
 * from the loaded core bridge, valid for the life of the registration.
 */
bool temporalio_perl_bridge_forwarding_register(struct TemporalioPerlBridgeQueue *q,
                                                const void *target,
                                                const void *message,
                                                const void *timestamp_millis,
                                                const void *fields_json);

/**
 * Release the forwarding registry held by `q`. A no-op unless `q` is the
 * currently registered queue (so a non-forwarding runtime's shutdown never
 * clears another runtime's registration). Called from `Runtime->shutdown`
 * before the queue is freed.
 */
void temporalio_perl_bridge_forwarding_unregister(struct TemporalioPerlBridgeQueue *q);

/**
 * Trampoline for core's `TemporalCoreForwardedLogCallback` (kind 7). Reads
 * the log's target/message/timestamp/fields-JSON via core's accessors,
 * deep-copies each string into shim-owned buffers, and pushes a kind-7 entry
 * onto the registered forwarding queue. A null registry (forwarding torn down
 * mid-flight) drops the log. No `user_data`: routing is via the registry.
 *
 * # Safety
 * `log` must be the valid `ForwardedLog` pointer core passes for the life of
 * this call; it must not be used after the callback returns.
 */
void temporalio_perl_bridge_forwarded_log_callback(uint32_t level,
                                                   const struct TemporalCoreForwardedLog *log);

/**
 * Address of the forwarded-log trampoline, for the `forward_to` slot of
 * `TemporalCoreLoggingOptions`.
 */
void *temporalio_perl_bridge_forwarded_log_callback_ptr(void);

/**
 * Free the shim-owned kind-7 log buffers of a drained entry. Called by the
 * Perl drain after it copies the target/message/fields strings out of the
 * entry. Idempotent (null pointers no-op); undrained entries are freed by
 * `Entry::drop` at queue free instead.
 *
 * # Safety
 * `entry` must point at a drained `TemporalioPerlBridgeEntry` written by
 * `temporalio_perl_bridge_queue_drain`, not yet freed.
 */
void temporalio_perl_bridge_forwarded_log_free(struct TemporalioPerlBridgeEntry *entry);

/**
 * Allocate a queue signalling `signal_fd` (eventfd, or pipe write-end as
 * the portable fallback — detected via fstat). The fd must be non-blocking;
 * the queue borrows it and never closes it.
 */
struct TemporalioPerlBridgeQueue *temporalio_perl_bridge_queue_new(int32_t signal_fd);

/**
 * Free the queue, dropping any undrained entries. The caller must guarantee
 * no further pushes (no pending async calls hold a pair into this queue).
 *
 * # Safety
 * `q` must be a pointer returned by `temporalio_perl_bridge_queue_new` that
 * has not already been freed.
 */
void temporalio_perl_bridge_queue_free(struct TemporalioPerlBridgeQueue *q);

/**
 * Pair `q` with a Perl-side callback id. The returned pointer is the
 * `user_data` argument for sdk-core-c-bridge async calls. Single-shot: the
 * trampoline frees it after enqueueing the completion entry. This is how
 * multiple runtimes each route completions to their own queue.
 */
void *temporalio_perl_bridge_user_data_new(struct TemporalioPerlBridgeQueue *q,
                                           uint64_t callback_id);

/**
 * Non-blocking drain, called from the Perl main thread when the signal fd
 * reads ready. Clears the eventfd, then pops up to `out_buf_capacity`
 * entries into `out_buf` and returns the count. Call in a loop until it
 * returns 0. ByteArray pointers in the entries must be freed by the caller.
 *
 * # Safety
 * `q` must be a live queue pointer and `out_buf` must point to at least
 * `out_buf_capacity` writable `TemporalioPerlBridgeEntry` slots.
 */
size_t temporalio_perl_bridge_queue_drain(struct TemporalioPerlBridgeQueue *q,
                                          struct TemporalioPerlBridgeEntry *out_buf,
                                          size_t out_buf_capacity);

/**
 * Trampoline for `TemporalCoreWorkerPollCallback` (kind 1).
 *
 * # Safety
 * `user_data` must be a pointer from `temporalio_perl_bridge_user_data_new`
 * not yet consumed by any trampoline.
 */
void temporalio_perl_bridge_worker_poll_callback(void *user_data,
                                                 const TemporalCoreByteArray *success,
                                                 const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreWorkerCallback` (kind 2).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_worker_callback(void *user_data, const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientConnectCallback` (kind 3).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_connect_callback(void *user_data,
                                                    TemporalCoreConnection *success,
                                                    const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientRpcCallCallback` (kind 4). The
 * `failure_message` rides in `fail_ba`.
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_rpc_call_callback(void *user_data,
                                                     const TemporalCoreByteArray *success,
                                                     uint32_t status_code,
                                                     const TemporalCoreByteArray *failure_message,
                                                     const TemporalCoreByteArray *failure_details);

/**
 * Trampoline for `TemporalCoreEphemeralServerStartCallback` (kind 5).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_start_callback(void *user_data,
                                                            TemporalCoreEphemeralServer *success,
                                                            const TemporalCoreByteArray *success_target,
                                                            const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreEphemeralServerShutdownCallback` (kind 6).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_shutdown_callback(void *user_data,
                                                               const TemporalCoreByteArray *fail);

/**
 * Address of the worker-poll trampoline, for passing as the callback
 * argument to sdk-core-c-bridge functions.
 */
void *temporalio_perl_bridge_worker_poll_callback_ptr(void);

/**
 * Address of the worker trampoline.
 */
void *temporalio_perl_bridge_worker_callback_ptr(void);

/**
 * Address of the client-connect trampoline.
 */
void *temporalio_perl_bridge_client_connect_callback_ptr(void);

/**
 * Address of the client-rpc-call trampoline.
 */
void *temporalio_perl_bridge_client_rpc_call_callback_ptr(void);

/**
 * Address of the ephemeral-server-start trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_start_callback_ptr(void);

/**
 * Address of the ephemeral-server-shutdown trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_shutdown_callback_ptr(void);

/**
 * Parse a `TemporalCoreWorkerOptions` built by the caller and return a
 * newline-delimited `field=value` summary covering every field in struct
 * order, as a NUL-terminated string. Free the result with
 * [`temporalio_perl_bridge_string_free`]. Debug-only: this exists so the
 * Perl SDK's marshalling can be verified empirically (plan P0.10) without a
 * server connection.
 *
 * # Safety
 * `options` must be null or point to a fully initialized
 * `TemporalCoreWorkerOptions` whose pointers remain valid for the call.
 */
char *temporalio_perl_bridge_debug_worker_options(const TemporalCoreWorkerOptions *options);

/**
 * Free a string returned by [`temporalio_perl_bridge_debug_worker_options`].
 *
 * # Safety
 * `s` must be null or a pointer previously returned by this crate's
 * string-returning functions, not yet freed.
 */
void temporalio_perl_bridge_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TEMPORALIO_PERL_BRIDGE_H */
