#ifndef TEMPORALIO_PERL_BRIDGE_H
#define TEMPORALIO_PERL_BRIDGE_H

/* Generated by cbindgen from temporalio-perl-bridge — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TemporalCoreByteArray TemporalCoreByteArray;
typedef struct TemporalCoreConnection TemporalCoreConnection;
typedef struct TemporalCoreEphemeralServer TemporalCoreEphemeralServer;
typedef struct TemporalCoreWorkerOptions TemporalCoreWorkerOptions;
typedef struct TemporalCoreCustomMetricAttribute TemporalCoreCustomMetricAttribute;

/**
 * `kind` discriminator values, 1..6 in spec section 3 trampoline order, plus
 * the kind-7 log-forwarding entry (spec section 28.1). Kind 7 differs from
 * 1..6: it carries no `callback_id` (no pending Future) and owns its buffers
 * shim-side, freed via `temporalio_perl_bridge_forwarded_log_free`.
 */
#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER_POLL 1

#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER 2

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_CONNECT 3

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_RPC_CALL 4

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_START 5

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_SHUTDOWN 6

#define TEMPORALIO_PERL_BRIDGE_KIND_FORWARDED_LOG 7

/**
 * Which marshalled meter request the drain must run. The Perl side switches on
 * this tag; the body fields carry the request's payload (see `MeterRequest`).
 */
#define TEMPORALIO_PERL_BRIDGE_METER_REQ_METRIC_NEW 1

#define TEMPORALIO_PERL_BRIDGE_METER_REQ_ATTRIBUTES_NEW 2

#define TEMPORALIO_PERL_BRIDGE_METER_REQ_METRIC_FREE 3

#define TEMPORALIO_PERL_BRIDGE_METER_REQ_ATTRIBUTES_FREE 4

#define TEMPORALIO_PERL_BRIDGE_METER_REQ_METER_FREE 5

/**
 * Thread-safe completion queue: an unbounded `SegQueue` plus the signal fd.
 * One allocation per `Temporalio::Core::Runtime` instance.
 */
typedef struct TemporalioPerlBridgeQueue TemporalioPerlBridgeQueue;

/**
 * Opaque borrow of sdk-core-c-bridge's `ForwardedLog`. The shim never
 * dereferences this — it only passes the pointer back to core's
 * `temporal_core_forwarded_log_*` accessors, which are valid only for the
 * duration of the `forward_to` callback (the log is freed the instant the
 * callback returns).
 */
typedef struct TemporalCoreForwardedLog {
  uint8_t _private[0];
} TemporalCoreForwardedLog;

/**
 * One queued completion. `kind` discriminates which trampoline fired (1..6)
 * and therefore which fields are meaningful. ByteArray pointers must be
 * freed by the Perl side via `temporal_core_byte_array_free`.
 */
typedef struct TemporalioPerlBridgeEntry {
  uint64_t callback_id;
  /**
   * Tagged union discriminator, 1..6 in trampoline declaration order.
   */
  uint8_t kind;
  /**
   * Common: success / fail byte arrays (null when absent).
   */
  const TemporalCoreByteArray *success_ba;
  const TemporalCoreByteArray *fail_ba;
  /**
   * Client connect / ephemeral server start success handle.
   */
  void *success_handle;
  /**
   * RPC call extras (fail_ba carries the failure_message). For a kind-7
   * forwarded-log entry, `rpc_status_code` carries the forwarded log level
   * (0..4 = Trace..Error).
   */
  uint32_t rpc_status_code;
  const TemporalCoreByteArray *rpc_failure_details;
  /**
   * Ephemeral server start target string.
   */
  const TemporalCoreByteArray *ephemeral_target;
  /**
   * Kind-7 forwarded-log payload (spec section 28.1). These three buffers
   * are deep copies owned by the shim (NUL-terminated C strings), freed by
   * `temporalio_perl_bridge_forwarded_log_free` after the Perl drain reads
   * them, or by `Entry::drop` for undrained entries at queue free. They are
   * null for every kind other than 7.
   */
  char *log_target;
  char *log_message;
  char *log_fields_json;
  /**
   * Kind-7 forwarded-log timestamp (milliseconds since the Unix epoch).
   */
  uint64_t log_timestamp_ms;
} TemporalioPerlBridgeEntry;

/**
 * A borrowed byte slice as returned by core's forwarded-log accessors,
 * matching `TemporalCoreByteArrayRef` (data may be null/zero-length).
 */
typedef struct ForwardedLogByteArrayRef {
  const uint8_t *data;
  size_t size;
} ForwardedLogByteArrayRef;

/**
 * One bucketed record snapshot the Perl meter pulls on drain: which metric and
 * attribute set, the record kind (1=integer, 2=float, 3=duration), and the
 * summed value. Floats and integers share `value` (f64) — integer/duration
 * records sum as i64 but are widened for the single snapshot shape, which is
 * exact for the magnitudes metrics produce.
 */
typedef struct TemporalioPerlBridgeMeterRecord {
  uint64_t metric_id;
  uint64_t attributes_id;
  /**
   * 1 = integer, 2 = float, 3 = duration (ms).
   */
  uint8_t record_kind;
  double value;
  /**
   * Number of record calls folded into `value` (for histogram/gauge the
   * Perl meter may want the count; counters only need the sum).
   */
  uint64_t count;
} TemporalioPerlBridgeMeterRecord;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Claim the process-global forwarding registry for `q`, recording the four
 * core accessor function pointers (passed as opaque from Perl). Returns true
 * on success, false if a runtime already forwards logs (the caller raises
 * Argument). The compare-and-set on the active flag makes the claim race-free
 * across runtimes constructed concurrently.
 *
 * # Safety
 * The four pointers must be the live `temporal_core_forwarded_log_*` symbols
 * from the loaded core bridge, valid for the life of the registration.
 */
bool temporalio_perl_bridge_forwarding_register(struct TemporalioPerlBridgeQueue *q,
                                                const void *target,
                                                const void *message,
                                                const void *timestamp_millis,
                                                const void *fields_json);

/**
 * Release the forwarding registry held by `q`. A no-op unless `q` is the
 * currently registered queue (so a non-forwarding runtime's shutdown never
 * clears another runtime's registration). Called from `Runtime->shutdown`
 * before the queue is freed.
 */
void temporalio_perl_bridge_forwarding_unregister(struct TemporalioPerlBridgeQueue *q);

/**
 * Trampoline for core's `TemporalCoreForwardedLogCallback` (kind 7). Reads
 * the log's target/message/timestamp/fields-JSON via core's accessors,
 * deep-copies each string into shim-owned buffers, and pushes a kind-7 entry
 * onto the registered forwarding queue. A null registry (forwarding torn down
 * mid-flight) drops the log. No `user_data`: routing is via the registry.
 *
 * # Safety
 * `log` must be the valid `ForwardedLog` pointer core passes for the life of
 * this call; it must not be used after the callback returns.
 */
void temporalio_perl_bridge_forwarded_log_callback(uint32_t level,
                                                   const struct TemporalCoreForwardedLog *log);

/**
 * Address of the forwarded-log trampoline, for the `forward_to` slot of
 * `TemporalCoreLoggingOptions`.
 */
void *temporalio_perl_bridge_forwarded_log_callback_ptr(void);

/**
 * Free the shim-owned kind-7 log buffers of a drained entry. Called by the
 * Perl drain after it copies the target/message/fields strings out of the
 * entry. Idempotent (null pointers no-op); undrained entries are freed by
 * `Entry::drop` at queue free instead.
 *
 * # Safety
 * `entry` must point at a drained `TemporalioPerlBridgeEntry` written by
 * `temporalio_perl_bridge_queue_drain`, not yet freed.
 */
void temporalio_perl_bridge_forwarded_log_free(struct TemporalioPerlBridgeEntry *entry);

/**
 * Claim the process-global meter registry for `queue`. Returns true on
 * success, false if a meter is already active (Perl raises Argument). The
 * compare-and-set makes the claim race-free across concurrently constructed
 * runtimes.
 *
 * # Safety
 * `queue` must be a live queue pointer for the registry's lifetime.
 */
bool temporalio_perl_bridge_meter_register(struct TemporalioPerlBridgeQueue *queue);

/**
 * Release the meter registry held by `queue` (no-op unless it is the active
 * one). Called from `Runtime->shutdown` after the worker/runtime that drove
 * the meter is gone, so no callback can still be in flight.
 *
 * # Safety
 * Must be called only after core has stopped invoking the meter callbacks.
 */
void temporalio_perl_bridge_meter_unregister(struct TemporalioPerlBridgeQueue *queue);

/**
 * `metric_new`: allocate a handle id, park a create request for the main-thread
 * drain (which runs the Perl `create_metric`), and return the id immediately.
 * Never blocks, never calls Perl — safe on any thread including reentrantly on
 * the main thread (spec section 28.2 spike resolution).
 */
const void *temporalio_perl_bridge_meter_metric_new(TemporalCoreByteArrayRef name,
                                                    TemporalCoreByteArrayRef description,
                                                    TemporalCoreByteArrayRef unit,
                                                    int32_t kind);

void temporalio_perl_bridge_meter_metric_free(const void *metric);

void temporalio_perl_bridge_meter_record_integer(const void *metric,
                                                 uint64_t value,
                                                 const void *attributes);

void temporalio_perl_bridge_meter_record_float(const void *metric,
                                               double value,
                                               const void *attributes);

void temporalio_perl_bridge_meter_record_duration(const void *metric,
                                                  uint64_t value_ms,
                                                  const void *attributes);

/**
 * `attributes_new`: decode the borrowed attribute array into owned copies,
 * allocate a handle id, park a create request, and return the id immediately
 * (the main-thread drain runs the Perl `new_attributes`). `append_from` is a
 * prior attributes handle (0/null = none). Never blocks, never calls Perl.
 */
const void *temporalio_perl_bridge_meter_attributes_new(const void *append_from,
                                                        const TemporalCoreCustomMetricAttribute *attributes,
                                                        size_t attributes_size);

void temporalio_perl_bridge_meter_attributes_free(const void *attributes);

/**
 * `meter_free`: per the header the custom meter "is freed by a callback within
 * itself". Parked so the Perl meter can release per-meter state on the drain.
 * The `meter` argument is the core meter struct pointer (unused — Perl owns its
 * own meter object via the registry).
 */
void temporalio_perl_bridge_meter_meter_free(const void *_meter);

/**
 * Pop the next parked create/free request into a heap box and return a raw
 * pointer to it (null if the queue is empty). The Perl drain reads the
 * request's fields via the `req_*` accessors, runs the Perl method, then frees
 * the box with `temporalio_perl_bridge_meter_free_request`. Returns the tag via
 * `*out_tag`.
 *
 * # Safety
 * `out_tag` must be a writable `u8` slot.
 */
const void *temporalio_perl_bridge_meter_next_request(uint8_t *out_tag);

/**
 * Free a request box returned by `temporalio_perl_bridge_meter_next_request`
 * once the Perl drain has read its fields.
 *
 * # Safety
 * `request` must be a pointer from `meter_next_request`, not yet freed.
 */
void temporalio_perl_bridge_meter_free_request(const void *request);

/**
 * The shim-allocated handle id for a create request (metric_new/attributes_new).
 */
uint64_t temporalio_perl_bridge_meter_req_new_id(const void *request);

/**
 * metric_new name (borrowed; valid only while the request is parked).
 */
struct ForwardedLogByteArrayRef temporalio_perl_bridge_meter_req_name(const void *request);

struct ForwardedLogByteArrayRef temporalio_perl_bridge_meter_req_description(const void *request);

struct ForwardedLogByteArrayRef temporalio_perl_bridge_meter_req_unit(const void *request);

int32_t temporalio_perl_bridge_meter_req_kind(const void *request);

uint64_t temporalio_perl_bridge_meter_req_free_id(const void *request);

uint64_t temporalio_perl_bridge_meter_req_append_from_id(const void *request);

size_t temporalio_perl_bridge_meter_req_attr_count(const void *request);

/**
 * attribute key at index `i` (borrowed).
 */
struct ForwardedLogByteArrayRef temporalio_perl_bridge_meter_req_attr_key(const void *request,
                                                                          size_t i);

/**
 * attribute value type at index `i` (1=String,2=Int,3=Float,4=Bool), 0 if out
 * of range.
 */
int32_t temporalio_perl_bridge_meter_req_attr_value_type(const void *request, size_t i);

struct ForwardedLogByteArrayRef temporalio_perl_bridge_meter_req_attr_string(const void *request,
                                                                             size_t i);

int64_t temporalio_perl_bridge_meter_req_attr_int(const void *request, size_t i);

double temporalio_perl_bridge_meter_req_attr_float(const void *request, size_t i);

bool temporalio_perl_bridge_meter_req_attr_bool(const void *request, size_t i);

/**
 * Drain the aggregation table into `out_buf` (up to `out_buf_capacity`
 * records), clearing what is drained. Returns the count written. Call in a
 * loop until it returns 0. The Perl meter applies each record to its own
 * counters/histograms/gauges.
 *
 * # Safety
 * `out_buf` must point to at least `out_buf_capacity` writable record slots.
 */
size_t temporalio_perl_bridge_meter_drain_records(struct TemporalioPerlBridgeMeterRecord *out_buf,
                                                  size_t out_buf_capacity);

void *temporalio_perl_bridge_meter_metric_new_ptr(void);

void *temporalio_perl_bridge_meter_metric_free_ptr(void);

void *temporalio_perl_bridge_meter_record_integer_ptr(void);

void *temporalio_perl_bridge_meter_record_float_ptr(void);

void *temporalio_perl_bridge_meter_record_duration_ptr(void);

void *temporalio_perl_bridge_meter_attributes_new_ptr(void);

void *temporalio_perl_bridge_meter_attributes_free_ptr(void);

void *temporalio_perl_bridge_meter_meter_free_ptr(void);

/**
 * Allocate a queue signalling `signal_fd` (eventfd, or pipe write-end as
 * the portable fallback — detected via fstat). The fd must be non-blocking;
 * the queue borrows it and never closes it.
 */
struct TemporalioPerlBridgeQueue *temporalio_perl_bridge_queue_new(int32_t signal_fd);

/**
 * Free the queue, dropping any undrained entries. The caller must guarantee
 * no further pushes (no pending async calls hold a pair into this queue).
 *
 * # Safety
 * `q` must be a pointer returned by `temporalio_perl_bridge_queue_new` that
 * has not already been freed.
 */
void temporalio_perl_bridge_queue_free(struct TemporalioPerlBridgeQueue *q);

/**
 * Pair `q` with a Perl-side callback id. The returned pointer is the
 * `user_data` argument for sdk-core-c-bridge async calls. Single-shot: the
 * trampoline frees it after enqueueing the completion entry. This is how
 * multiple runtimes each route completions to their own queue.
 */
void *temporalio_perl_bridge_user_data_new(struct TemporalioPerlBridgeQueue *q,
                                           uint64_t callback_id);

/**
 * Non-blocking drain, called from the Perl main thread when the signal fd
 * reads ready. Clears the eventfd, then pops up to `out_buf_capacity`
 * entries into `out_buf` and returns the count. Call in a loop until it
 * returns 0. ByteArray pointers in the entries must be freed by the caller.
 *
 * # Safety
 * `q` must be a live queue pointer and `out_buf` must point to at least
 * `out_buf_capacity` writable `TemporalioPerlBridgeEntry` slots.
 */
size_t temporalio_perl_bridge_queue_drain(struct TemporalioPerlBridgeQueue *q,
                                          struct TemporalioPerlBridgeEntry *out_buf,
                                          size_t out_buf_capacity);

/**
 * Trampoline for `TemporalCoreWorkerPollCallback` (kind 1).
 *
 * # Safety
 * `user_data` must be a pointer from `temporalio_perl_bridge_user_data_new`
 * not yet consumed by any trampoline.
 */
void temporalio_perl_bridge_worker_poll_callback(void *user_data,
                                                 const TemporalCoreByteArray *success,
                                                 const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreWorkerCallback` (kind 2).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_worker_callback(void *user_data, const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientConnectCallback` (kind 3).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_connect_callback(void *user_data,
                                                    TemporalCoreConnection *success,
                                                    const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientRpcCallCallback` (kind 4). The
 * `failure_message` rides in `fail_ba`.
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_rpc_call_callback(void *user_data,
                                                     const TemporalCoreByteArray *success,
                                                     uint32_t status_code,
                                                     const TemporalCoreByteArray *failure_message,
                                                     const TemporalCoreByteArray *failure_details);

/**
 * Trampoline for `TemporalCoreEphemeralServerStartCallback` (kind 5).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_start_callback(void *user_data,
                                                            TemporalCoreEphemeralServer *success,
                                                            const TemporalCoreByteArray *success_target,
                                                            const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreEphemeralServerShutdownCallback` (kind 6).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_shutdown_callback(void *user_data,
                                                               const TemporalCoreByteArray *fail);

/**
 * Address of the worker-poll trampoline, for passing as the callback
 * argument to sdk-core-c-bridge functions.
 */
void *temporalio_perl_bridge_worker_poll_callback_ptr(void);

/**
 * Address of the worker trampoline.
 */
void *temporalio_perl_bridge_worker_callback_ptr(void);

/**
 * Address of the client-connect trampoline.
 */
void *temporalio_perl_bridge_client_connect_callback_ptr(void);

/**
 * Address of the client-rpc-call trampoline.
 */
void *temporalio_perl_bridge_client_rpc_call_callback_ptr(void);

/**
 * Address of the ephemeral-server-start trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_start_callback_ptr(void);

/**
 * Address of the ephemeral-server-shutdown trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_shutdown_callback_ptr(void);

/**
 * Parse a `TemporalCoreWorkerOptions` built by the caller and return a
 * newline-delimited `field=value` summary covering every field in struct
 * order, as a NUL-terminated string. Free the result with
 * [`temporalio_perl_bridge_string_free`]. Debug-only: this exists so the
 * Perl SDK's marshalling can be verified empirically (plan P0.10) without a
 * server connection.
 *
 * # Safety
 * `options` must be null or point to a fully initialized
 * `TemporalCoreWorkerOptions` whose pointers remain valid for the call.
 */
char *temporalio_perl_bridge_debug_worker_options(const TemporalCoreWorkerOptions *options);

/**
 * Free a string returned by [`temporalio_perl_bridge_debug_worker_options`].
 *
 * # Safety
 * `s` must be null or a pointer previously returned by this crate's
 * string-returning functions, not yet freed.
 */
void temporalio_perl_bridge_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TEMPORALIO_PERL_BRIDGE_H */
