#ifndef TEMPORALIO_PERL_BRIDGE_H
#define TEMPORALIO_PERL_BRIDGE_H

/* Generated by cbindgen from temporalio-perl-bridge — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TemporalCoreByteArray TemporalCoreByteArray;
typedef struct TemporalCoreConnection TemporalCoreConnection;
typedef struct TemporalCoreEphemeralServer TemporalCoreEphemeralServer;

/**
 * `kind` discriminator values, 1..6 in spec section 3 trampoline order.
 */
#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER_POLL 1

#define TEMPORALIO_PERL_BRIDGE_KIND_WORKER 2

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_CONNECT 3

#define TEMPORALIO_PERL_BRIDGE_KIND_CLIENT_RPC_CALL 4

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_START 5

#define TEMPORALIO_PERL_BRIDGE_KIND_EPHEMERAL_SERVER_SHUTDOWN 6

/**
 * Thread-safe completion queue: an unbounded `SegQueue` plus the signal fd.
 * One allocation per `Temporalio::Core::Runtime` instance.
 */
typedef struct TemporalioPerlBridgeQueue TemporalioPerlBridgeQueue;

/**
 * One queued completion. `kind` discriminates which trampoline fired (1..6)
 * and therefore which fields are meaningful. ByteArray pointers must be
 * freed by the Perl side via `temporal_core_byte_array_free`.
 */
typedef struct TemporalioPerlBridgeEntry {
  uint64_t callback_id;
  /**
   * Tagged union discriminator, 1..6 in trampoline declaration order.
   */
  uint8_t kind;
  /**
   * Common: success / fail byte arrays (null when absent).
   */
  const TemporalCoreByteArray *success_ba;
  const TemporalCoreByteArray *fail_ba;
  /**
   * Client connect / ephemeral server start success handle.
   */
  void *success_handle;
  /**
   * RPC call extras (fail_ba carries the failure_message).
   */
  uint32_t rpc_status_code;
  const TemporalCoreByteArray *rpc_failure_details;
  /**
   * Ephemeral server start target string.
   */
  const TemporalCoreByteArray *ephemeral_target;
} TemporalioPerlBridgeEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocate a queue signalling `signal_fd` (eventfd, or pipe write-end as
 * the portable fallback — detected via fstat). The fd must be non-blocking;
 * the queue borrows it and never closes it.
 */
struct TemporalioPerlBridgeQueue *temporalio_perl_bridge_queue_new(int32_t signal_fd);

/**
 * Free the queue, dropping any undrained entries. The caller must guarantee
 * no further pushes (no pending async calls hold a pair into this queue).
 *
 * # Safety
 * `q` must be a pointer returned by `temporalio_perl_bridge_queue_new` that
 * has not already been freed.
 */
void temporalio_perl_bridge_queue_free(struct TemporalioPerlBridgeQueue *q);

/**
 * Pair `q` with a Perl-side callback id. The returned pointer is the
 * `user_data` argument for sdk-core-c-bridge async calls. Single-shot: the
 * trampoline frees it after enqueueing the completion entry. This is how
 * multiple runtimes each route completions to their own queue.
 */
void *temporalio_perl_bridge_user_data_new(struct TemporalioPerlBridgeQueue *q,
                                           uint64_t callback_id);

/**
 * Non-blocking drain, called from the Perl main thread when the signal fd
 * reads ready. Clears the eventfd, then pops up to `out_buf_capacity`
 * entries into `out_buf` and returns the count. Call in a loop until it
 * returns 0. ByteArray pointers in the entries must be freed by the caller.
 *
 * # Safety
 * `q` must be a live queue pointer and `out_buf` must point to at least
 * `out_buf_capacity` writable `TemporalioPerlBridgeEntry` slots.
 */
size_t temporalio_perl_bridge_queue_drain(struct TemporalioPerlBridgeQueue *q,
                                          struct TemporalioPerlBridgeEntry *out_buf,
                                          size_t out_buf_capacity);

/**
 * Trampoline for `TemporalCoreWorkerPollCallback` (kind 1).
 *
 * # Safety
 * `user_data` must be a pointer from `temporalio_perl_bridge_user_data_new`
 * not yet consumed by any trampoline.
 */
void temporalio_perl_bridge_worker_poll_callback(void *user_data,
                                                 const TemporalCoreByteArray *success,
                                                 const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreWorkerCallback` (kind 2).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_worker_callback(void *user_data, const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientConnectCallback` (kind 3).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_connect_callback(void *user_data,
                                                    TemporalCoreConnection *success,
                                                    const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreClientRpcCallCallback` (kind 4). The
 * `failure_message` rides in `fail_ba`.
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_client_rpc_call_callback(void *user_data,
                                                     const TemporalCoreByteArray *success,
                                                     uint32_t status_code,
                                                     const TemporalCoreByteArray *failure_message,
                                                     const TemporalCoreByteArray *failure_details);

/**
 * Trampoline for `TemporalCoreEphemeralServerStartCallback` (kind 5).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_start_callback(void *user_data,
                                                            TemporalCoreEphemeralServer *success,
                                                            const TemporalCoreByteArray *success_target,
                                                            const TemporalCoreByteArray *fail);

/**
 * Trampoline for `TemporalCoreEphemeralServerShutdownCallback` (kind 6).
 *
 * # Safety
 * See `temporalio_perl_bridge_worker_poll_callback`.
 */
void temporalio_perl_bridge_ephemeral_server_shutdown_callback(void *user_data,
                                                               const TemporalCoreByteArray *fail);

/**
 * Address of the worker-poll trampoline, for passing as the callback
 * argument to sdk-core-c-bridge functions.
 */
void *temporalio_perl_bridge_worker_poll_callback_ptr(void);

/**
 * Address of the worker trampoline.
 */
void *temporalio_perl_bridge_worker_callback_ptr(void);

/**
 * Address of the client-connect trampoline.
 */
void *temporalio_perl_bridge_client_connect_callback_ptr(void);

/**
 * Address of the client-rpc-call trampoline.
 */
void *temporalio_perl_bridge_client_rpc_call_callback_ptr(void);

/**
 * Address of the ephemeral-server-start trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_start_callback_ptr(void);

/**
 * Address of the ephemeral-server-shutdown trampoline.
 */
void *temporalio_perl_bridge_ephemeral_server_shutdown_callback_ptr(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TEMPORALIO_PERL_BRIDGE_H */
